### ISSUE TITLE
There is a theoretical max amount of particles (that is relatively low)

### ISSUE THREAD

**Issue by chrisblakley** [jh3y/shooting-stars#1]
I've been having fun playing with this JS source, and it seems like the "amount" parameter eventually stops adding particles (even if its set ridiculously high). I was hoping to get a dense star field (using small points of white circles instead of the star shape), and I got them to look how I want, but I can't seem to break that invisible particle limit.

I can't seem to get more than 15-20 particles visible on the canvas at once...

Very cool script, though. Thanks for sharing it.

**Comment by jh3y** [comment]
Hey @chrisblakley,

I think I understand the effect you're going for :smile: 

It may only seem to get to a certain amount because of the probability of adding a new particle when it comes to the loop. I think the way I've written it, if you were to loosen the constraints around that piece of logic, you could theoretically add 60 particles per second.

This is off the top of my head, so I'll need to take a little look at what I put in there and see if I can parametize it for this scenario.

No problems :smile: 

@jh3y

**Comment by jh3y** [comment]
@chrisblakley I added a config option `particleRenderProbability`. This should be a float between `0` and `1`. For example; `0.95`.

In the logic, `Math.Random` is used and if it is higher than that `particleRenderProbability` and the particle pool size hasn't reached the `amount`, then a new particle is rendered.

Hope that helps :smile:

**Comment by chrisblakley** [comment]
Very cool- thanks!
